// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    facility_detail: {
        name: "facility_detail";
        parameters: {
          /** STRING - use sql.string() */
          facility_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          organization_type: string;
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType STRING */
          operator_type: string;
          /** @sqlType STRING */
          address_line1: string;
          /** @sqlType STRING */
          address_line2: string;
          /** @sqlType STRING */
          address_line3: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          postcode: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          procedure_text: string;
          /** @sqlType STRING */
          equipment: string;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          number_doctors: string;
          /** @sqlType STRING */
          capacity: string;
          /** @sqlType STRING */
          year_established: string;
          /** @sqlType STRING */
          websites: string;
          /** @sqlType STRING */
          source_urls: string;
          /** @sqlType STRING */
          phone_numbers: string;
          /** @sqlType STRING */
          email: string;
        }>;
      };
    field_completeness: {
        name: "field_completeness";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          field_name: string;
          /** @sqlType DECIMAL(26,1) */
          pct_complete: number;
        }>;
      };
    quality_summary: {
        name: "quality_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_facilities: number;
          /** @sqlType BIGINT */
          high_priority: number;
          /** @sqlType BIGINT */
          medium_priority: number;
          /** @sqlType BIGINT */
          low_priority: number;
        }>;
      };
    review_queue: {
        name: "review_queue";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType INT */
          missing_field_count: number;
          /** @sqlType BOOLEAN */
          missing_description: boolean;
          /** @sqlType BOOLEAN */
          missing_doctors: boolean;
          /** @sqlType BOOLEAN */
          missing_capacity: boolean;
          /** @sqlType BOOLEAN */
          missing_year: boolean;
          /** @sqlType BOOLEAN */
          missing_specialties: boolean;
          /** @sqlType STRING */
          description_preview: string;
        }>;
      };
    state_distribution: {
        name: "state_distribution";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
          /** @sqlType DECIMAL(26,1) */
          desc_pct: number;
          /** @sqlType DECIMAL(26,1) */
          capability_pct: number;
        }>;
      };
  }
}
